### PR TITLE
3.0.5

### PR DESCRIPTION
**Pull request by glachance**
I don't really want to become package maintainer for swig... i tought I would at least write the update and let you push it.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Hey @glachance. Did you test your changes? It was a little irresponsible of me to take this on...I don't remember how to push the update. Could you remind me how to build the package?

**Comment by chrisdembia** [comment]
I know I can upload the package at this site https://chocolatey.org/packages/upload once it's built. I don't remember the command to build it though.

**Comment by glachance** [comment]
yep.  all tested.  allow the merge, then download it locally, "choco pack" will make the nupkg, then upload.  if you want to test it locally before sending its "choco install swig -source %cd%" while in the folder

**Comment by glachance** [comment]
if you want to test it locally before sending its "choco install swig -source %cd%" while in the folder

**Comment by chrisdembia** [comment]
image

**Comment by glachance** [comment]
hey! i didnt see you managed to pull through.  congrats!

**Comment by chrisdembia** [comment]
Hahaha :blush: . Thanks for the help.

**Pull request merged**
